/truesense/truesense_camera:
  ros__parameters:
    modulation_frequency: 8.0
    frame_rate: 30

/truesense/tof_sensor_rear:
  ros__parameters:
    flip_horizontal: false
    flip_vertical: false
    #desired_location: rear
    stream_type: distance_amplitude

/truesense/tof_sensor_left:
  ros__parameters:
    flip_horizontal: false
    flip_vertical: false
    desired_location: left
    stream_type: distance_amplitude
/automatic_exposure:
  ros__parameters:
    ae_aw_gain: 0.0
    ae_d_gain: 0.0001
    ae_feedback_type: recursive control
    ae_gain_sched_atten: 0.2
    ae_gain_sched_thresh: 40.0
    ae_i_gain: 0.0
    ae_max_integration_time_us: 4000
    ae_min_integration_time_us: 100
    ae_p_gain: 0.025
    ae_q_gain: 0.0025
    ae_rc_speed_factor: 0.1
    ae_roi_bottom_px: 80
    ae_roi_left_px: 80
    ae_roi_right_px: 80
    ae_roi_top_px: 80
    ae_target_exp_avg_alpha: 0.95
    ae_target_mean_amp: 400
    ae_target_peak_amp: 1000
    ae_target_type: mean amplitude
    ae_verbose: false
    ae_weight_bottom: 1.0
    ae_weight_center: 10.0
    ae_weight_left: 2.0
    ae_weight_right: 2.0
    ae_weight_top: 1.0
    ctlr_output_decimation: 1
    int_deadband_us: 4
    rate: 5.0
    use_sim_time: false
    with_autoexposure: true

/tf:
  x: 3.85
  y: -0.4
  z: 2.70
  yaw: 0.15
  pitch: -0.05
  roll: 0.0
  destination: base_footprint

/truesense/filter_node:
  ros__parameters:
    use_xyz: true
    use_clock: false
    sensor_frame_id: unknown

    background_sub_on: false
    fg_update_frame_ct: 0
    imgmask_crop_on: false
    cornercrop_on: false
    cornercrop_show_image: false

    imgfilter_on: true
    imgfilter_diameter: 3
    imgfilter_sigma_range: 0.3
    imgfilter_sigma_space: 5.0

    imgmask_ampthresh_on: true
    imgmask_ampthresh_max: 2000.0
    imgmask_ampthresh_min_far: 50.0
    imgmask_ampthresh_min_near: 50.0
    imgmask_ampthresh_switch_distance_m: 5.0

    imgmask_snr_on: true
    imgmask_snr_thresh: 5.0
    imgmask_snr_ambient_const_m: 0.36
    imgmask_snr_amplitude_const_m: 0.32
    
    satrm_on: true
    satrm_amplitude: 1500.0
    satrm_dilation_size: 3
    satrm_fill_type: mean
    satrm_inpaint_radius: 5.0
    
    temporal_filter_on: false 
    set_masked_points_to_zero: true
    temporal_filter_alpha_min: 0.1
    temporal_filter_dst_max: 0.5
    
    xmask_on: false
    ymask_on: false
    zmask_on: false

    use_sim_time: false
    qos_overrides./parameter_events.publisher.depth: 1000
    qos_overrides./parameter_events.publisher.durability: volatile
    qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: reliable

/truesense/detection_node:
  ros__parameters:
    use_clock: false
    publish_full_cloud: true
    frame_id: base_footprint

    boxfit_method: min variance
    boxfit_angle_increment_deg: 1.0
    boxfit_min_npts: 10

    cluster_on: true
    cluster_far_distance_m: 8.0
    cluster_incl_distance_far_m: 0.2
    cluster_incl_distance_near_m: 0.1
    cluster_min_npts_percloud_far: 20
    cluster_min_npts_percloud_near: 50
    cluster_sharp_angle_tol_deg: 10.0
    
    ground_removal_on: true
    ground_removal_alphamax_lb_deg: 5.0
    ground_removal_alphamax_lb_dist_m: 2.5
    ground_removal_alphamax_ub_deg: 5.0
    ground_removal_alphamax_ub_dist_m: 4.0
    ground_removal_groundlevel_m: 0.15
    ground_removal_medianfilter_ksize: 0
    ground_removal_savgol_wsize: 5
    ground_removal_searchdir: row ascending

    use_sim_time: false
    qos_overrides./parameter_events.publisher.depth: 1000
    qos_overrides./parameter_events.publisher.durability: volatile
    qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: reliable

/path_filtered/clearance_node:
  ros__parameters:
    steering_angle_deg: 0.0
    steering_wheel_deadband_deg: 30.0
    steering_ratio: 0.0572
    axle_dist_behind_cam: 1.98
    wheel_base: 3.75

    # As measured (with requested buffer)
    # width: 2.24
    # z_min: 1.9
    # z_max: 2.87

    # Add a little space to get better bounding boxes on objects
    width: 2.24
    z_min: 1.9
    z_max: 2.80
  
    min_area: 10000.0
    min_object_height: 0.5
    
    use_sim_time: false

/path_filtered/detection_node:
  ros__parameters:
    use_clock: false
    publish_ful_cloud: false
    frame_id: base_footprint

    boxfit_method: min variance
    boxfit_angle_increment_deg: 1.0
    boxfit_min_npts: 100

    cluster_on: true
    cluster_far_distance_m: 8.0
    cluster_incl_distance_far_m: 0.2
    cluster_incl_distance_near_m: 0.1
    cluster_min_npts_percloud_far: 10
    cluster_min_npts_percloud_near: 10
    cluster_sharp_angle_tol_deg: 10.0
    
    ground_removal_on: false

    use_sim_time: false
    qos_overrides./parameter_events.publisher.depth: 1000
    qos_overrides./parameter_events.publisher.durability: volatile
    qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: reliable

/path_filtered/tracking_node:
  ros__parameters:
    frame_id: base_footprint
    verbose: false
    show_person_only: false
    mot_tracking_on: true

    obj_height_lb_m: 0.0
    obj_z_lb_m: 0.0

    box_tracker_type: ConstAcceleration
    forward_predict_if_not_detected: false
    kf_cov_init: 1000000.0
    kf_mea_noise_m: 0.5
    kf_proc_var: 2.0 
    cpe_on: true
    cpe_brake_g: 0.0
    cpe_collision_clearance_m: 0.15
    cpe_ego_cm2front_m: 3.85
    cpe_ego_cm2rear_m: 2.88
    cpe_ego_width_m: 2.24
    cpe_prob_thresh: 0.99
    cpe_show_collisionbox: true
    cpe_ttc_thresh_s: 0.2
    cpe_with_ttc_prob: true

    min_intertrack_dist_m: 1.0
    track2obj_distance_ub_m: 1.0
    birth_count: 1
    death_count: 4
    speed_thresh_mps: 0.5
    dynamic_count_thresh: 10
    dynamic_prob_thresh: 0.99
    
    use_sim_time: false
    qos_overrides./parameter_events.publisher.depth: 1000
    qos_overrides./parameter_events.publisher.durability: volatile
    qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: reliable

/path_filtered/alert_node:
  ros__parameters:
    k_velocity: 0.05
    reset_state_machine: false
    alert_timeout_s: 2.0

    activation_max_prob: 0.6
    activation_min_prob: 0.3

    low_max_dist: 1.0
    low_max_t_react: 2.0

    med_max_dist: 0.5
    med_max_t_react: 1.5

    high_max_dist: 0.25
    high_max_t_react: 1.0
  
    tone_path: config/beep-15.wav
    low_tone_bpm: 70
    med_tone_bpm: 110
    high_tone_bpm: 170

    use_sim_time: false
